# -*- coding: utf-8 -*-
"""chan vese.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1-9bFJdRi7ZipbVptp9t9BxekPOVmPx
"""

import tensorflow_datasets as tfds
import tensorflow as tf
from skimage.segmentation import chan_vese
import matplotlib.pyplot as plt
from skimage import data, img_as_float
import numpy as np

"""télechargement de dataset"""

dataset = tfds.load("oxford_iiit_pet:4.0.0", as_supervised=False)
train = dataset["train"]

"""Métrique d'évaluation"""

def dice(mask, seg):

    #mask=mask.numpy()
    #seg=seg.numpy()
    # flatten
    mask = mask.flatten()
    seg = seg.flatten()

    inter = np.sum(mask * seg)

    return (2 * inter) / (
        np.sum(mask) + np.sum(seg) + 1e-8
    )


def iou(mask, seg):

    #mask=mask.numpy()
    #seg=seg.numpy()
    # flatten
    mask = mask.flatten()
    seg = seg.flatten()

    inter = np.sum(mask * seg)

    union = np.sum(mask + seg) - inter

    return inter / (union + 1e-8)

def preprocess(sample):

    # IMAGE
    image = tf.image.resize(sample["image"], (128, 128))
    image = tf.image.rgb_to_grayscale(image)
    image = tf.squeeze(image).numpy().astype(np.float32) / 255.0

    # MASK
    mask = tf.image.resize(
        sample["segmentation_mask"],
        (128, 128),
        method="nearest"
    )

    mask = mask[:, :, 0].numpy()

    # objet = classe 1
    #mask =(mask == 1).astype(np.float32)
     # objet = classe 1 + 3
    # fond = classe 2
    mask = ((mask == 1) | (mask == 3)).astype(np.float32)

    return image, mask
def run_chanvese(image):

    image = image.astype(np.float32)
    seg = chan_vese(
        image,
        mu=0.25,
        lambda1=1,
        lambda2=1,
        max_num_iter=700,
        init_level_set="checkerboard"
        #init_level_set="disk"



    )

    return seg.astype(np.float32)

"""Test sur la base de chats et de chiens"""

for i, sample in enumerate(train.take(5)):

    image = sample["image"]
    mask = sample["segmentation_mask"]
    img, gt = preprocess(sample)
    seg = run_chanvese(img)
    d = dice(gt, seg)
    j = iou(gt, seg)
    plt.figure(figsize=(10,4))

    #plt.subplot(1,3,1)
    #plt.imshow(img)
    #plt.title("Image")

    #image originale
    plt.subplot(1,3,1)
    plt.imshow(image)
    plt.title("Image")


    plt.subplot(1,3,2)
    plt.imshow(gt, cmap="gray")
    plt.title("Ground Truth")

    plt.subplot(1,3,3)
    plt.imshow(seg, cmap="gray")
    plt.title(f"Chan-Vese\nDice={d:.3f} | IoU={j:.3f}")

    plt.show()

results = []

for sample in train.take(50):
    img_rgb = sample["image"]
    img, mask = preprocess(sample)
    seg = run_chanvese(img)

    # métriques
    d = dice(mask, seg)
    j = iou(mask, seg)

    results.append((d, j))

    print(f"Dice: {d:.3f} | IoU: {j:.3f}")


dice_mean = np.mean([r[0] for r in results])
iou_mean = np.mean([r[1] for r in results])

print("\n=== Métriques d'évaluation ===")
print(f"Dice mean: {dice_mean:.4f}")
print(f"IoU mean: {iou_mean:.4f}")

print("mask unique:", np.unique(mask))
print("seg unique:", np.unique(seg))

"""Test sur des images synthétiques"""

#image = img_as_float(data.camera())
image = img_as_float(data.coins())
# Feel free to play around with the parameters to see how they impact the result
cv = chan_vese(
    image,
    mu=0.25,
    lambda1=1,
    lambda2=1,
    tol=1e-3,
    max_num_iter=200,
    dt=0.5,
    init_level_set="checkerboard",
    extended_output=True,
)

fig, axes = plt.subplots(2, 2, figsize=(8, 8))
ax = axes.flatten()

ax[0].imshow(image, cmap="gray")
ax[0].set_axis_off()
ax[0].set_title("Original Image", fontsize=12)

ax[1].imshow(cv[0], cmap="gray")
ax[1].set_axis_off()
title = f'Chan-Vese segmentation - {len(cv[2])} iterations'
ax[1].set_title(title, fontsize=12)

ax[2].imshow(cv[1], cmap="gray")
ax[2].set_axis_off()
ax[2].set_title("Final Level Set", fontsize=12)

ax[3].plot(cv[2])
ax[3].set_title("Evolution of energy over iterations", fontsize=12)

fig.tight_layout()
plt.show()